#+TITLE: Capstone Documentation

* C

Design and develop a fully functional data product that addresses your identified business problem or organizational need. Include each of the following attributes as they are the minimum required elements for the product:

** one descriptive method and one non-descriptive (predictive or prescriptive) method

*** Descriptive Method

- 10 most common sentence structures
- Average lyric length
- 5-number analysis of lyric length

** collected or available datasets

** decision-support functionality

** ability to support featurizing, parsing, cleaning, and wrangling datasets

** methods and algorithms supporting data exploration and preparation

** data visualization functionalities for data exploration and inspection

** implementation of interactive queries

** implementation of machine-learning methods and algorithms

** functionalities to evaluate the accuracy of the data product

** industry-appropriate security features

** tools to monitor and maintain the product

** a user-friendly, functional dashboard that includes at least three visualization types


* Documentation

D.  Create each of the following forms of documentation for the product you have developed:

** Business Vision

Provide rhyming lyric suggestions optionally constrained by syllable count.

** Data Sets

See ~resources/darklyrics-markov.tpt~

** Data Analysis

See ~src/com/owoga/darklyrics/core.clj~

See https://github.com/eihli/prhyme

** Assessment

See visualization of rhyme suggestion in action.

See perplexity?

** Visualizations

See visualization of smoothing technique.

See wordcloud

** Accuracy

•  assessment of the product’s accuracy

** Testing

•  the results from the data product testing, revisions, and optimization based on the provided plans, including screenshots

** Source

•  source code and executable file(s)

** Quick Start

•  a quick start guide summarizing the steps necessary to install and use the product

* Notes

http-kit doesn't support https so no need to bother with keystore stuff like you would with jetty. Just proxy from haproxy.
